# Site settings
author: Thomas Gray
title: Title TBD
header-img: img/home-bg.png
email: tgray017@gmail.com
copyright_name: Thomas Gray
description: > # this means to ignore newlines until "baseurl:"
  Subtitle TBD
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  tgray017

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
